### ISSUE TITLE
Notes from the interim (Oct 2019)

### ISSUE THREAD

**Issue by raphaelrobert** [mlswg/mls-federation#1]
- drop client fanout
 - specify why (policy enforcement, metadata protection)
 - incorporated comments from SV
 - check if it is necessary to define server-to-server message formats
 - only one domain is responsible for a group

**Comment by ianopolous** [comment]
I'm very interested in the details of this, but was unable to attend the interim meeting. 

Does this mean that we are explicitly ruling out client fanout entirely? What metadata are we trying to protect here? You could in theory protect all the metadata with client fanout over Tor for example. 

Does domain here mean domain name? Why is that relevant? (I'd expect MLS to be independent of DNS)

The kind of federated delivery service I'm hoping to be able to use with MLS is logically an append only list of messages published by each member. Where each member can read any other members queue and pull messages they don't have into their own queue (they push their own messages to their own queue only). This allows for diverse P2P topologies, and bandwidth efficient routing. This would be compatible with both [SSB](https://www.scuttlebutt.nz/) and [Peergos](https://github.com/peergos/peergos).

**Comment by raphaelrobert** [comment]
> Does this mean that we are explicitly ruling out client fanout entirely? What metadata are we trying to protect here? You could in theory protect all the metadata with client fanout over Tor for example.

TreeKEM has the requirement of total ordering of handshake messages which doesn't work with client fanout. Therefore we drop the idea of client fanout until we have a better proposal on how to solve this.

> Does domain here mean domain name? Why is that relevant? (I'd expect MLS to be independent of DNS)

`Domain` is more conceptual, it doesn't have to be an actual domain name.

**Comment by raphaelrobert** [comment]
Addressed in #2.
